### ISSUE TITLE
Complete upgrade to Lagom 1.5

### ISSUE THREAD

**Issue by ignasi35** [lagom/shopping-cart-java#12]
Lagom 1.5 handles Akka Management and Cluster bootstrap already so custom code like:

https://github.com/lagom/shopping-cart-java/blob/1.5.x/shopping-cart/src/main/java/com/example/shoppingcart/impl/ShoppingCartModule.java#L15

is not necessary.

Other bits and pieces no longer necessary:

 * explicit dependencies which lagom 1.5 brings in transitively
 * etc... (see https://github.com/lagom/shopping-cart-scala/issues/13)

**Comment by marcospereira** [comment]
Can we close this now? See https://github.com/lagom/shopping-cart-java/pull/14.

**Comment by ignasi35** [comment]
Yes. Closing
