### ISSUE TITLE
Delete branch `master`

### ISSUE THREAD

**Issue by ignasi35** [lagom/shopping-cart-java#16]
@jroper I noticed `master` still exists in the repo and I think it's an unwanted push.

IIUC, the only diverging commit is 83855a07dab380fde3f5510004adf7d358538295 which should be ported to `1.4.x`  and `1.5.x` in #9 and #11, right?

**Comment by marcospereira** [comment]
Any other reason to keep `master` branch?

**Comment by jroper** [comment]
Deleted. I pushed this not realising that the branch structure had changed.
